name: Build and Deploy Image

on:
  workflow_dispatch:
    inputs:
        environment:
          type: environment
          description: Select the environment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: 'Echo Vars'
        run: echo "${{ toJson(vars) }}"
