name: Build and Deploy Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        run: |
          echo "${{ vars.ENV }}"
          echo "${{ toJson(env) }}"
          echo "${{ toJson(github) }}"
